project:
  type: book

book:
  title: "JDemetra+ online documentation"
  author: "Anna Smyk, Alain Quartier-la-Tente, Tanguy Barthelemy, Karsten Webel"
  date: "12/22/2022"
  page-navigation: true
  chapters:
    - index.qmd
    - G-what-is-jd.qmd
    - part: P_Algorithms.qmd
      chapters:
        - A-sa.qmd
        - A-sa-hf.qmd
        - A-outlier-detection.qmd
        - A-calendar-and-input.qmd
        - A-benchmarking.qmd
        - A-trend-cycle-estimation.qmd
        - A-nowcasting.qmd
    - part: P_Tools.qmd
      chapters:
        - T-graphical-user-interface.qmd
        - T-r-packages.qmd
        - T-Production-tools-cruncher-QR.qmd
        - T-rev-policies-production.qmd
        - T-plug-ins.qmd
    - part: P_Methods.qmd
      chapters:
        - M-spectral-analysis.qmd
        - M-reg-arima-modelling.qmd
        - M-X11-decomposition.qmd
        - M-STL-decomposition.qmd
        - M-SEATS-decomposition.qmd
        - M-Trend-Estimation-Local-Polynomials.qmd
        - M-tests.qmd
        - M-state-space-framework.qmd
        - M-Temp-Disagg-Bench.qmd
        - references.qmd


bibliography: references.bib

format:
  html:
    theme: 
        - united
        - custom.scss
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: source

