project:
  type: book

book:
  title: "JDemetra+ online documentation"
  author: "Stace documentation group"
  date: "12/01/2022"
  chapters:
    - index.qmd
    - what-is-jd.qmd
    - quick-start.qmd
    - main-features.qmd
    - outlier-detection.qmd
    - sa-hf.qmd
    - benchmarking.qmd
    - trend-cycle-estimation.qmd
    - nowcasting.qmd
    - graphical-user-interface.qmd
    - r-packages.qmd
    - plug-ins.qmd
    - production.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

